=== Wiesmak/tracen-player/schema/quizzes.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Quizzes Schema",
  "description": "An array of quizzes",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": {
        "type": "string",
        "description": "Unique identifier for the quiz"
      },
      "title": {
        "type": "string",
        "description": "Title of the quiz"
      },
      "image": {
        "type": "string",
        "description": "Image associated with the quiz"
      },
      "description": {
        "type": "string",
        "description": "Description of the quiz"
      },
      "type": {
        "type": "string",
        "enum": ["uma", "truefalse", "match"],
        "description": "The type of the quiz"
      },
      "questions": {
        "type": "array",
        "items": {
          "type": "string"
        },
        "description": "List of question identifiers or references associated with the quiz"
      }
    },
    "required": [
      "id",
      "title",
      "image",
      "description",
      "type",
      "questions"
    ],
    "additionalProperties": false
  }
}

=== Wiesmak/tracen-player/public/data/quizzes.json
[
  {
    "id": "uma-zoom",
    "title": "Test Zoom Quiz",
    "image": "uma.png",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam gravida turpis eu tortor congue rutrum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis mattis placerat laoreet.",
    "type": "uma",
    "questions": [
      "q_uma-zoom_admire_groove_racewear",
      "q_uma-zoom_admire_vega_racewear",
      "q_uma-zoom_agnes_digital_racewear",
      "q_uma-zoom_agnes_tachyon_racewear",
      "q_uma-zoom_air_groove_racewear",
      "q_uma-zoom_air_messiah_racewear",
      "q_uma-zoom_air_shakur_racewear",
      "q_uma-zoom_almond_eye_racewear",
      "q_uma-zoom_aston_machan_racewear",
      "q_uma-zoom_bamboo_memory_racewear",
      "q_uma-zoom_believe_racewear",
      "q_uma-zoom_biko_pegasus_racewear",
      "q_uma-zoom_biwa_hayahide_racewear",
      "q_uma-zoom_blast_onepiece_racewear",
      "q_uma-zoom_bubble_gum_fellow_racewear",
      "q_uma-zoom_buena_vista_racewear",
      "q_uma-zoom_calstone_light_o_racewear",
      "q_uma-zoom_cesario_racewear",
      "q_uma-zoom_cheval_grand_racewear",
      "q_uma-zoom_chrono_genesis_racewear",
      "q_uma-zoom_copano_rickey_racewear",
      "q_uma-zoom_curren_bouquetd'or_racewear",
      "q_uma-zoom_curren_chan_racewear",
      "q_uma-zoom_daiichi_ruby_racewear",
      "q_uma-zoom_daitaku_helios_racewear",
      "q_uma-zoom_daiwa_scarlet_racewear",
      "q_uma-zoom_dantsu_flame_racewear",
      "q_uma-zoom_daring_heart_racewear",
      "q_uma-zoom_daring_tact_racewear",
      "q_uma-zoom_dream_journey_racewear",
      "q_uma-zoom_duramente_racewear",
      "q_uma-zoom_durandal_racewear",
      "q_uma-zoom_eishin_flash_racewear",
      "q_uma-zoom_el_condor_pasa_racewear",
      "q_uma-zoom_epiphaneia_racewear",
      "q_uma-zoom_espoir_city_racewear",
      "q_uma-zoom_fenomeno_racewear",
      "q_uma-zoom_fine_motion_racewear",
      "q_uma-zoom_forever_young_racewear",
      "q_uma-zoom_fujimasa_march_racewear",
      "q_uma-zoom_fuji_kiseki_racewear",
      "q_uma-zoom_furioso_racewear",
      "q_uma-zoom_fusaichi_pandora_racewear",
      "q_uma-zoom_gentildonna_racewear",
      "q_uma-zoom_gold_city_racewear",
      "q_uma-zoom_gold_ship_racewear",
      "q_uma-zoom_gran_alegria_racewear",
      "q_uma-zoom_grass_wonder_racewear",
      "q_uma-zoom_haru_urara_racewear",
      "q_uma-zoom_hishi_akebono_racewear",
      "q_uma-zoom_hishi_amazon_racewear",
      "q_uma-zoom_hishi_miracle_racewear",
      "q_uma-zoom_hokko_tarumae_racewear",
      "q_uma-zoom_ikuno_dictus_racewear",
      "q_uma-zoom_inari_one_racewear",
      "q_uma-zoom_ines_fujin_racewear",
      "q_uma-zoom_jungle_pocket_racewear",
      "q_uma-zoom_k.s.miracle_racewear",
      "q_uma-zoom_katsuragi_ace_racewear",
      "q_uma-zoom_kawakami_princess_racewear",
      "q_uma-zoom_king_halo_racewear",
      "q_uma-zoom_kiseki_racewear",
      "q_uma-zoom_kitasan_black_racewear",
      "q_uma-zoom_logotype_racewear",
      "q_uma-zoom_loves_only_you_racewear",
      "q_uma-zoom_lucky_lilac_racewear",
      "q_uma-zoom_manhattan_cafe_racewear",
      "q_uma-zoom_marche_lorraine_racewear",
      "q_uma-zoom_maruzensky_racewear",
      "q_uma-zoom_marvelous_sunday_racewear",
      "q_uma-zoom_matikanefukukitaru_racewear",
      "q_uma-zoom_matikanetannhauser_racewear",
      "q_uma-zoom_mayano_top_gun_racewear",
      "q_uma-zoom_meisho_doto_racewear",
      "q_uma-zoom_mejiro_ardan_racewear",
      "q_uma-zoom_mejiro_bright_racewear",
      "q_uma-zoom_mejiro_dober_racewear",
      "q_uma-zoom_mejiro_mcqueen_racewear",
      "q_uma-zoom_mejiro_palmer_racewear",
      "q_uma-zoom_mejiro_ramonu_racewear",
      "q_uma-zoom_mejiro_ryan_racewear",
      "q_uma-zoom_mihono_bourbon_racewear",
      "q_uma-zoom_mr._c.b._racewear",
      "q_uma-zoom_nakayama_festa_racewear",
      "q_uma-zoom_narita_brian_racewear",
      "q_uma-zoom_narita_taishin_racewear",
      "q_uma-zoom_narita_top_road_racewear",
      "q_uma-zoom_neo_universe_racewear",
      "q_uma-zoom_nice_nature_racewear",
      "q_uma-zoom_nishino_flower_racewear",
      "q_uma-zoom_north_flight_racewear",
      "q_uma-zoom_no_reason_racewear",
      "q_uma-zoom_oguri_cap_racewear",
      "q_uma-zoom_orfevre_racewear",
      "q_uma-zoom_red_desire_racewear",
      "q_uma-zoom_rhein_kraft_racewear",
      "q_uma-zoom_rice_shower_racewear",
      "q_uma-zoom_rose_kingdom_racewear",
      "q_uma-zoom_royce_and_royce_racewear",
      "q_uma-zoom_rulership_racewear",
      "q_uma-zoom_sakura_bakushin_o_racewear",
      "q_uma-zoom_sakura_chitose_o_racewear",
      "q_uma-zoom_sakura_chiyono_o_racewear",
      "q_uma-zoom_sakura_laurel_racewear",
      "q_uma-zoom_samson_big_racewear",
      "q_uma-zoom_satono_crown_racewear",
      "q_uma-zoom_satono_diamond_racewear",
      "q_uma-zoom_seeking_the_pearl_racewear",
      "q_uma-zoom_seiun_sky_racewear",
      "q_uma-zoom_shinko_windy_racewear",
      "q_uma-zoom_silence_suzuka_racewear",
      "q_uma-zoom_sirius_symboli_racewear",
      "q_uma-zoom_smart_falcon_racewear",
      "q_uma-zoom_sounds_of_earth_racewear",
      "q_uma-zoom_special_week_racewear",
      "q_uma-zoom_st-2_v3",
      "q_uma-zoom_stay_gold_racewear",
      "q_uma-zoom_still_in_love_racewear",
      "q_uma-zoom_super_creek_racewear",
      "q_uma-zoom_sweep_tosho_racewear",
      "q_uma-zoom_symboli_kris_s_racewear",
      "q_uma-zoom_symboli_rudolf_racewear",
      "q_uma-zoom_t.m._opera_o_racewear",
      "q_uma-zoom_taiki_shuttle_racewear",
      "q_uma-zoom_tamamo_cross_racewear",
      "q_uma-zoom_tanino_gimlet_racewear",
      "q_uma-zoom_tap_dance_city_racewear",
      "q_uma-zoom_tokai_teio_racewear",
      "q_uma-zoom_tosen_jordan_racewear",
      "q_uma-zoom_transcend_racewear",
      "q_uma-zoom_tsurumaru_tsuyoshi_racewear",
      "q_uma-zoom_twin_turbo_racewear",
      "q_uma-zoom_verxina_racewear",
      "q_uma-zoom_victoire_pisa_racewear",
      "q_uma-zoom_vivlos_racewear",
      "q_uma-zoom_vodka_racewear",
      "q_uma-zoom_winning_ticket_racewear",
      "q_uma-zoom_win_variation_racewear",
      "q_uma-zoom_wonder_acute_racewear",
      "q_uma-zoom_yaeno_muteki_racewear",
      "q_uma-zoom_yamanin_zephyr_racewear",
      "q_uma-zoom_yukino_bijin_racewear",
      "q_uma-zoom_zenno_rob_roy_racewear"
    ]
  },
  {
    "id": "uma-test",
    "title": "Test quiz",
    "image": "uma.png",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam gravida turpis eu tortor congue rutrum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis mattis placerat laoreet.",
    "type": "uma",
    "questions": [
      "q_uma-test_admire_groove_racewear",
      "q_uma-test_admire_vega_racewear",
      "q_uma-test_agnes_digital_racewear",
      "q_uma-test_agnes_tachyon_racewear",
      "q_uma-test_air_groove_racewear",
      "q_uma-test_air_messiah_racewear",
      "q_uma-test_air_shakur_racewear",
      "q_uma-test_almond_eye_racewear",
      "q_uma-test_aston_machan_racewear",
      "q_uma-test_bamboo_memory_racewear",
      "q_uma-test_believe_racewear",
      "q_uma-test_biko_pegasus_racewear",
      "q_uma-test_biwa_hayahide_racewear",
      "q_uma-test_blast_onepiece_racewear",
      "q_uma-test_bubble_gum_fellow_racewear",
      "q_uma-test_buena_vista_racewear",
      "q_uma-test_calstone_light_o_racewear",
      "q_uma-test_cesario_racewear",
      "q_uma-test_cheval_grand_racewear",
      "q_uma-test_chrono_genesis_racewear",
      "q_uma-test_copano_rickey_racewear",
      "q_uma-test_curren_bouquetd'or_racewear",
      "q_uma-test_curren_chan_racewear",
      "q_uma-test_daiichi_ruby_racewear",
      "q_uma-test_daitaku_helios_racewear",
      "q_uma-test_daiwa_scarlet_racewear",
      "q_uma-test_dantsu_flame_racewear",
      "q_uma-test_daring_heart_racewear",
      "q_uma-test_daring_tact_racewear",
      "q_uma-test_dream_journey_racewear",
      "q_uma-test_duramente_racewear",
      "q_uma-test_durandal_racewear",
      "q_uma-test_eishin_flash_racewear",
      "q_uma-test_el_condor_pasa_racewear",
      "q_uma-test_epiphaneia_racewear",
      "q_uma-test_espoir_city_racewear",
      "q_uma-test_fenomeno_racewear",
      "q_uma-test_fine_motion_racewear",
      "q_uma-test_forever_young_racewear",
      "q_uma-test_fujimasa_march_racewear",
      "q_uma-test_fuji_kiseki_racewear",
      "q_uma-test_furioso_racewear",
      "q_uma-test_fusaichi_pandora_racewear",
      "q_uma-test_gentildonna_racewear",
      "q_uma-test_gold_city_racewear",
      "q_uma-test_gold_ship_racewear",
      "q_uma-test_gran_alegria_racewear",
      "q_uma-test_grass_wonder_racewear",
      "q_uma-test_haru_urara_racewear",
      "q_uma-test_hishi_akebono_racewear",
      "q_uma-test_hishi_amazon_racewear",
      "q_uma-test_hishi_miracle_racewear",
      "q_uma-test_hokko_tarumae_racewear",
      "q_uma-test_ikuno_dictus_racewear",
      "q_uma-test_inari_one_racewear",
      "q_uma-test_ines_fujin_racewear",
      "q_uma-test_jungle_pocket_racewear",
      "q_uma-test_k.s.miracle_racewear",
      "q_uma-test_katsuragi_ace_racewear",
      "q_uma-test_kawakami_princess_racewear",
      "q_uma-test_king_halo_racewear",
      "q_uma-test_kiseki_racewear",
      "q_uma-test_kitasan_black_racewear",
      "q_uma-test_logotype_racewear",
      "q_uma-test_loves_only_you_racewear",
      "q_uma-test_lucky_lilac_racewear",
      "q_uma-test_manhattan_cafe_racewear",
      "q_uma-test_marche_lorraine_racewear",
      "q_uma-test_maruzensky_racewear",
      "q_uma-test_marvelous_sunday_racewear",
      "q_uma-test_matikanefukukitaru_racewear",
      "q_uma-test_matikanetannhauser_racewear",
      "q_uma-test_mayano_top_gun_racewear",
      "q_uma-test_meisho_doto_racewear",
      "q_uma-test_mejiro_ardan_racewear",
      "q_uma-test_mejiro_bright_racewear",
      "q_uma-test_mejiro_dober_racewear",
